### ISSUE TITLE
Resupply Lockers Next to Doors

### ISSUE THREAD

**Issue by Kestrelguy** [slayerofdrosophila/tf2mapper#1]
The map conversion seems to be placing resupply lockers next to doors when there are walls available.

**Comment by slayerofdrosophila** [comment]
Thanks for checking the project out. Sorry for not getting to the issues tab.

Currently it assumes that a BLU spawn will only face down/right and a RED spawn up/left (and so it can put the locker on the opposite corner). I will be working on some fix for this, probably by giving control as to where the spawn is oriented, and therefore where the locker can go.

**Comment by slayerofdrosophila** [comment]
Alright, now you can change the way spawns face by pressing "S" multiple times. The resupply cabinet will be on the wall opposite the door. If this doesn't fix your problem, or is frustrating to use, please let me know. I am sorry for making you wait so long.
